import { CommunityPostType, KeywordType } from '@/types';

export const JobOfferDummy = [
  {
    id: 1,
    dDay: 12,
    title: '[2024 상반기 SK이노베이션] UX 디자이너 채용',
    category: 'UX',
    career: ['신입', '1~3년차'],
    imageUrl:
      'https://s3-alpha-sig.figma.com/img/f43c/2eb4/be33f8076106fc2e58de3b4a5f35075d?Expires=1705881600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=IpwKEzMwU~4tpJHY-Jl9YLmAyBZ9-w7ahSR22vjeS2k768qQY2XI2pSW80M3vFYTOVnVCQAFVAeB9L~EV9sNZx1uW0~QQtt1Qv5Vbtc3ojK2bj7MlNRquFEAWvFcG8CQuIdo5k9XRiLc1Uzy4t~SnJF3gD6eN9Tz5jcv8OnmcxVicHLtoPwFmZHQUiEn8dLU1LXTLUCHOTZMi4jjVGcyXJXdseJeh0suNGq8BWufZfK09f~thE34Nr5rkkvtAI8o0T5UnTmrP~~grMucyUj8hqjfwVxD61It~5oOo5a1NviMK~qtowbtAdCxQyhe-CCNRqxx~eNvhC88OXQJasphpg__',
    company: 'SK이노베이션',
  },
  {
    id: 2,
    dDay: 21,

    title: '[카카오] 카카오프렌즈 공간디자인 VMD_어시스턴트 채용',
    category: 'VMD',
    career: ['신입'],
    imageUrl:
      'https://s3-alpha-sig.figma.com/img/c41a/d6f0/22ceed93ded28ac06724035f8a6d3a77?Expires=1705881600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=Xtwr3lGxqKinlwRrIS~FCZ8uBgwmNFoD-ymw-gJD8tiOMKv9M-6NcwVgx5Gq6xLiYPYNmwgxJWApTSMDIBPjpKYkINnc4-5TBp2NlFrmNO4273aMg4EOVGsAUYeW1xNTPBVcOdL1hJyxvtZIdmBu4jSCowREFRt3Om1A0ciJruB2bBVy2a8pXkGe7wMKHdAQG1jizxkHEcyik1sX6ANrz2fj0vWf18XHGIYqINwY1qFck6xu9f2I~f-1WeraO6e-tJZckFwA61M5kIzEBPayWwx-23MJm5NwRTniWWK7BMmdRcjy8UHTiNwFf7Wa10nJrhvZxtrZ8SG3RXhWsimjaA__',
    company: '카카오',
  },
  {
    id: 3,
    dDay: 9,
    title: '[삼성웰스토리] 공간디자인 담당자 채용',
    category: 'VMD',
    career: ['5년차 이상'],
    imageUrl:
      'https://s3-alpha-sig.figma.com/img/1f30/a7dd/3b1bc3c3ec5f8e221e9cc0a94678b501?Expires=1705881600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=ZHTIIYOQ40Pgg0W5KBZ0XgX8Vk6ue3X6M3H9LCLURZCM9dwufSxV9ZChJ4TshKGelf1kKWOBAcameO4ISp0bahL18UOsBLTgp0Y93tdMEG7nxY-zokAm0ARsR~lc7PilbY3c5tnJZMLBq6VJoMLWPdqJWJM5TSHXOIGXiiJgqrXmCaRh0DIFkCbEyE~wPLVJ23tq-OPTdoGt8Pj3t4gZD~cgvCNiFu06M87gkdlGUj~Da9db6Y89kJEjdZgy6DGXEvzNQECqtjUEOoPPIdbjJIRob4kITH~k-L9JSYA7nQMDdaVvm6vvyjiViTP8U8e8S7lAssTAALGRq-X1vbqsvA__',
    company: '삼성웰스토리',
  },
  {
    id: 4,
    title: '[이랜드리테일] 광고디자인 인턴십 채용',
    category: '광고',
    career: ['신입'],
    imageUrl:
      'https://s3-alpha-sig.figma.com/img/afe2/764b/68bb371da6928c4b0eb7f91c543bf0be?Expires=1705881600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=VQYcHFUFnZ8KE4TYwpCFbPjOgzz3emC5ijp88-KDv3GHUaLPCc~-AUXp6z-pAzorwBCUL5EQD8JdmCOS-JYM3a2Z8TMRu7nUdPM8ZYH7lcEsl~13HTFbFVgReWy0UF92U9sAhEOq~I6Qjb-mlazAVtkiMcD6~71hbO72SAiRatmcNUTEBxyMjwPLhu~BLvfbTpGDEeOdXAjY0oQZqfIXHW6xUPGwu7q5cpPFoQr89YUvj6FOzjtHqgcMGVUXRY90JGBo74Ofw2MUO2CwIiLr~8gko9VUdhVUh451iRWKdUKob4V5s~QWlPNr47H7WNHmMsAjZ2WmBBqK8p25gMWQGA__',
    company: '이랜드리테일',
  },
  {
    id: 5,
    dDay: 50,
    title: '[신성통상(주)] R&D본부 디자인팀 경력',
    category: 'UX',
    career: ['3년차 이상'],
    imageUrl:
      'https://s3-alpha-sig.figma.com/img/b1bf/c704/08adddc0b1f425fb0002bb6848230b64?Expires=1705881600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=fmyJJJOoM-9Mz-hKUzMh6gmufPQ6wvhz3t~Tr6WnBjq~O3hGHGVlDASYBl4h3AKbGLF~F9hp8cxohYn3XpMeDrY9PC8qqRXU6nPH5vjMhlT6gP7zyTxPCB4Qj-aw4XpoFS1s4b9oMVjie0wT5ILzx3M0Dr~o15b~xS0HfIHB2oMykH50ynTYhplF6UZV0aMO9O1hdN7zKpTUiS7U9wEOVxtnnK0bVZC8QIdboeQTSuKYdHD2MlXA0mCXWBgUOlMZ5MC58ExSHK~heGk16GGjjD6eVHLSsBW3TrF4IGCHc~FNMZNeSoJnyjxIFeVMR-169temLRgtBJ3ABmNdkQyXIQ__',
    company: 'SK이노베이션',
  },
  {
    id: 6,
    title: '[크레텍책임] 디자인 신입/경력 채용',
    category: '제품',
    career: ['신입'],
    imageUrl:
      'https://s3-alpha-sig.figma.com/img/8bb3/6eaa/5d3fab3c631e8e2bfc7caa49aa4094cf?Expires=1705881600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=B-M09ZpvgnvR7p6GJCsex5Dz62NQ4HppupkUF8Y5-3qnjVJygzMoE1KNjNOQ8ARAuq9TaDuvvRPPetyVxzho2J8ASrzg2-QjAfkOlC3B0qjOQy1nDNF4dcJUThQ-1NP66Ac2CRWU5WoN7W4eUGbb8oWXgyVmvG~H1Y6sauS1E~28mpTFU6mjG-elKK-lDLAnHo32SBmEw2sGr8wwSJoRMSp8eFX177y17cAxK96JA7I5i-DaqjRi45X7vJRmNIJf1pc73-C-rpHjcykbRzGVCLbwfzicb4iG7XQj5b1AMXTZ0mtf9Dmt8ih6A8RBaVL~ZoaINxIePY0Yvkhs2AzPjg__',
    company: '크레텍책임',
  },
  {
    id: 7,
    title: '[애경산업] 2024 화장품컨텐츠 디자인 기획/제작 담당 계약직 채용',
    category: '콘텐츠',
    career: ['5년차 이상'],
    imageUrl:
      'https://s3-alpha-sig.figma.com/img/f3bf/f2df/b37de04c8a8e8b4cc9451cd8b5120020?Expires=1705881600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=IT6R2LjUGMSXA3THOFrIxhqg8OlaI6ciCqhutfswrepzAFJkdGD2L9nBFP9mq1Hw-O9UCJ9HX6njkTvogxxyn5UOO3VXZNh~UE2X7VLIyxMKvsvn6ba5923z-9C9p4YZRrHPdKNDU367UOsaTM7xLc49MeiOpSB5M6L1Q4SllcH3wzNZfnr4SSXac8zh5pXLJwO9JnxhVD4MtwRp1UOtP91RnO-8ehVaysDehjdjpPBIpeK84CyRY-EO297fxauJrXaUQvHWp95qQrab0UYBX8sWqfH1Y0tF8XKHWFn4PzwtvahN8hatCr1HE5jmk1fUMyGwapv006f5NpSncS4XKQ__',
    company: '애경산업',
  },
  {
    id: 8,
    title: '[(주)이프어데이] 웹디자인 신입 채용',
    category: '광고',
    career: ['신입'],
    imageUrl:
      'https://s3-alpha-sig.figma.com/img/612f/9ded/00fd05ece040eb287fd717f0743e3399?Expires=1705881600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=PjWuIiXACSCE1wYKRoHKeFRO62QkBPSezidDm9EcRM1osScnHiASM~2Smr1YSOyoXC3lxfFYTpx3-bRnBpJL196b~4h4Fx8PMNpiu6H~JDYD0PRhjedfmKH2Ykqvv7Q9uRkKp4qYTHeEh7jafluMmJy6E7pXFG6Z6T010oCizymoBHNKfBDHCEwWYLUtu5MXcz6GYJPYXmXznXVAcXpUJHULYs8uCAjDF70siQzwfgQZrlMpHxSd4t~LLcf3blA9p~d8RWeYqWx3wTfSYl668sQtxK77IMq~0ZMaIo~ydTwLwPttmngdvVWpjoamTZeYFYyu5sNSLKC~lS-Tg4Dvpg__',
    company: '이프어데이',
  },
];

export const PopularKeywordsDummy: KeywordType[] = [
  { content: '대외활동', rank: 'rise' },
  { content: 'UX디자인', rank: 'maintain' },
  { content: '인턴 프로그램', rank: 'decline' },
  { content: '재택 근무', rank: 'rise' },
  { content: '에이전시', rank: 'decline' },
  { content: '포트폴리오', rank: 'rise' },
  { content: '디자이너', rank: 'rise' },
  { content: '취업', rank: 'rise' },
  { content: '부트캠프 후기', rank: 'rise' },
  { content: '개발자 모집', rank: 'rise' },
];

export const CommunityPostDummy: CommunityPostType[] = [
  {
    title: '혹시 이번에 웅진씽크빅 합격 연락 받은사람?ㅜㅠ',
    content:
      '내가 이것저것 대외활동도 하고 면접도 나쁘지 않았는데, 아직 결과 안온듯,,ㅜㅠ 문자 받은사람있으신가요?',
    tags: ['회사', '취업', '인턴', '신입', '채용', '면접'],
    category: '질의응답',
    createdAt: '2024-01-02 18:30',
    likes: 224,
    comments: [
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
    ],
    views: 2680,
  },
  {
    title: 'UXUI 인턴형 프로그램 1기 후기',
    content:
      '이번에 인턴형 프로그램 1기에 참여한 무순죽순채순입니다. 10월부터 사전 직무교육 후에 팀 프로젝트를 진행했습니다.',
    tags: ['UX', '디자인', '인턴형프로그램', '후기', '취업', 'UI'],
    category: '스팩 후기',
    createdAt: '2024-01-02 18:30',
    likes: 12,
    comments: [
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
    ],
    views: 1892,
  },
  {
    title: '대학교에서 졸업준비위원회 한거 포폴에 넣어도 되나?',
    content:
      '내가 대학교에서 졸준위했는데 다같이 작업하긴 했는데 거의 내 디자인임. 그래서 포폴에 넣을건데 상관없나?',
    tags: ['디자인', '포트폴리오', '졸업전시'],
    category: '자유게시판',
    createdAt: '2024-01-09 18:20',
    likes: 23,
    comments: [
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
    ],
    views: 1720,
    thumbnail:
      'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?q=80&w=2052&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: '서브프로젝트 성공적인 후기',
    content:
      '드디어 성공적인 서브 프로젝트를 진행했다. 솔직히 여기저기서 힘들다는 이야기 많았지만, 이정도 일 줄은,, 그래도 작업물 보면 뿌듯함.',
    tags: ['서브프로젝트', '디자인', '후기'],
    category: '자유게시판',
    createdAt: '2024-01-02 18:30',
    likes: 46,
    comments: [
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
    ],
    views: 1588,
  },
  {
    title:
      '이번에 개발자로 취업하고 싶어서 스팩에서 개발자 대외활동 신청할건데 같이할 사람',
    content:
      '나는 어느정도 기초만 할 줄 아는데, 더 배우고 싶은 마음도 있고, 새로운 사람들도 많이 만나보고 싶음...',
    tags: ['개발자', '부트캠프', '대외활동', '취업'],
    category: '자유게시판',
    createdAt: '2024-01-02 18:30',
    likes: 11,
    comments: [
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
    ],
    views: 1243,
  },
  {
    title: 'UXUI 인턴형 프로그램 2기 후기',
    content:
      '내가 1기 놓치고 2기가 생각보다 금방 시작해서 지원했는데, 합격해서 진짜 열심히함. 1기보다 직무교육도 짧아서 걱정했는데, 나쁘지 않았음...',
    tags: ['UX', '디자인', '인턴형프로그램', '후기', '취업', 'UI'],
    category: '자유게시판',
    createdAt: '2024-01-06 18:30',
    likes: 187,
    comments: [
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
    ],
    views: 1176,
    thumbnail:
      'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?q=80&w=2052&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: '회사 이직..그거 어떻게 하는건데..',
    content:
      '이직할건데 일한지 이제 1년 4개월 넘음, 지금하면 좀 그런가,, 다들 언제 이직했어ㅜㅠㅜㅠㅜㅠ',
    tags: ['회사', '이직', '퇴사'],
    category: '자유게시판',
    createdAt: '2024-01-06 18:30',
    likes: 20,
    comments: [
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
    ],
    views: 1023,
  },
  {
    title: '개발자 부트캠프 후기',
    content:
      '개발자로 일하다가 쉬어갈겸, 부트캠프해서 실력 좀 키우고 왔는데, 역시 스팩 부트캠프는 진짜 믿고 하는 듯, 수준도 좋고 팀원들도 잘 만났음...',
    tags: ['개발자', '부트캠프', '후기', '취업'],
    category: '자유게시판',
    createdAt: '2024-01-09 14:30',
    likes: 12,
    comments: [
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
    ],
    views: 875,
    thumbnail:
      'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?q=80&w=2052&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: '대학생 3학년인데 대외활동 2개함,,,',
    content:
      '미대생이라 과제가 너무 많은데 이번에 3학년 올라가는데 대외활동 두개함,,이게 맞는건가,,,',
    tags: ['대학생', '디자인', '대외활동'],
    category: '자유게시판',
    createdAt: '2024-01-09 14:30',
    likes: 21,
    comments: [
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
    ],
    views: 731,
  },
  {
    title: '대기업을 퇴사한 이유',
    content:
      '저는 누구나 들으면 아는 대기업에서 디자이너로 일하고 있었습니다. 다른 사람들 모두 퇴사하는 이유가 있는데 저도 어린나이에도 불구하고 퇴사라...',
    tags: ['UX', '디자인', '회사', '디자이너', 'UI'],
    category: '자유게시판',
    createdAt: '2024-01-09 14:30',
    likes: 590,
    comments: [
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
    ],
    views: 650,
  },
  {
    title: '서브 프로젝트가 경력으로 들어가나요?',
    content:
      '제가 이력서나 포폴에 서브프로젝트를 적으려하는데 이걸 경력으로 쳐주나요? 잘 모르겠어요ㅜㅠ',
    tags: ['경력', '포트폴리오', '디자이너', '취업'],
    category: '자유게시판',
    createdAt: '2024-01-08 14:30',
    likes: 12,
    comments: [
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
    ],
    views: 632,
    thumbnail:
      'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?q=80&w=2052&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'UXUI 인턴형 프로그램 1기 후기',
    content:
      '이번에 인턴형 프로그램 1기에 참여한 무순죽순채순입니다. 10월부터 사전 직무교육 후에 팀 프로젝트를 진행했습니다.',
    tags: ['UX', '디자인', '인턴형프로그램', '후기', '취업', 'UI'],
    category: '스팩 후기',
    createdAt: '2024-01-02 18:30',
    likes: 10,
    comments: [
      { name: '', content: '', createdAt: '', likes: 0, comments: [] },
    ],
    views: 500,
  },
];
